sudo: false
language: python
python:
  - "3.6"
node_js:
  - "8"
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
install:
  - npm install
  - cp app/app/local_settings.py.dist app/app/local_settings.py
  - pip install -r requirements/test.txt
script:
  - npm run eslint
  - pytest -p no:ethereum
after_success:
  - pip install codecov
  - codecov
addons:
  postgresql: "9.6"
