sudo: false
language: python
python:
  - "3.6"
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
install:
  - cp app/app/local.env app/app/.env
  - pip install -r requirements/test.txt
script:
  - pytest
after_success:
  - pip install codecov
  - codecov
addons:
  postgresql: "9.6"
