version: '3'

services:
  db:
    image: postgres
  migration:
    build: .
    command: python app/manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    restart: always
    build: .
    command: bash docker-command.bash
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
    stdin_open: true
    tty: true
